name: bump

on:
  workflow_dispatch:
    inputs:
      majorVersion:
        description: Mandatory, when bumping a major version. Semver compatible version string (X.Y.Z). Must not be set for patch and minor version releases.
        required: false
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
            node-version-file: ".nvmrc"
            cache: pnpm
            registry-url: https://registry.npmjs.org

      - run: yarn install --frozen-lockfile
      - name: Setup git
        run: |
          git config --global user.email "cloud-sdk-js@github.com"
          git config --global user.name "cloud-sdk-js"
      - name: Push
        run: git push --follow-tags
